/**
 * Calculates the number of days between the current date and the provided last modified date.
 * Returns the number of days if the date is valid and not in the future, otherwise returns 0.
 *
 * @param lastModified - The last modified date as a string or Date object.
 * @returns The number of days ago the last modification occurred, or 0 if invalid.
 */
export const getDaysAgo = (lastModified: string | Date): number => {
	// Parse the last modified date
	const lastModifiedDate = typeof lastModified === "string" ? new Date(lastModified) : lastModified;
	
	// Check if the parsed date is valid
	if (isNaN(lastModifiedDate.getTime())) {
		console.warn(`Invalid date format: "${lastModified}". Returning 0.`);
		return 0;
	}
	
	const currentDate = new Date();
	
	// Calculate the difference in milliseconds
	const diffInMs = currentDate.getTime() - lastModifiedDate.getTime();
	
	// Handle future dates
	if (diffInMs < 0) {
		console.warn(`The provided date "${lastModified}" is in the future. Returning 0.`);
		return 0;
	}
	
	// Convert milliseconds to days
	const diffInDays = Math.floor(diffInMs / (1000 * 60 * 60 * 24));
	
	return diffInDays;
};

/**
 * utility to parse datestring into a Date object
 * @param dateString
 * @param format
 */
export function stringToDate(dateString: string, format: any= null): Date {
	format = format || dateString;
	let normalized: string = dateString.replace(/[^a-zA-Z0-9]/g, '-');
	let normalizedFormat: string = format.toLowerCase().replace(/[^a-zA-Z0-9]/g, '-');
	let formatItems: string[] = normalizedFormat.split('-');
	let dateItems: string[] = normalized.split('-');
	
	let monthIndex = formatItems.indexOf("mm");
	let dayIndex = formatItems.indexOf("dd");
	let yearIndex = formatItems.indexOf("yyyy");
	let hourIndex = formatItems.indexOf("hh");
	let minutesIndex = formatItems.indexOf("ii");
	let secondsIndex = formatItems.indexOf("ss");
	let timeZoneIndex = formatItems.indexOf("z")
	
	let today = new Date();
	let year: number = yearIndex > -1? parseInt(dateItems[yearIndex]) : today.getFullYear();
	let month: number = monthIndex > -1? parseInt(dateItems[monthIndex]) - 1 : today.getMonth() - 1;
	let day: number = dayIndex >- 1? parseInt(dateItems[dayIndex]) : today.getDate();
	
	let hour: number = hourIndex >-1? parseInt(dateItems[hourIndex]) : today.getHours();
	let minute: number = minutesIndex >-1? parseInt(dateItems[minutesIndex]) : today.getMinutes();
	let second: number = secondsIndex >-1? parseInt(dateItems[secondsIndex]) : today.getSeconds();
	let timeZone = timeZoneIndex >-1? dateItems[timeZoneIndex] : "missing";
	// console.log(dateItems);
	// console.log("timezone:", timeZone);
	
	return new Date(year, month, day, hour, minute, second);
}

// Example object
const model = {
	"model_id": "mock-model-001",
	"model_name": "Mock Model 1",
	"description": "This is a mock model for demonstration purposes.",
	"tags": ["mock", "example", "demo"],
	"license": "MIT",
	"author": "John Doe",
	"created_at": "2023-10-01T00:00:00Z",
	"last_modified": "2023-10-01T00:00:00Z",
	"downloads": 0,
	"likes": 0,
	"model_type": "transformer",
	"language": "en",
	"tasks": ["text-classification", "text-generation"],
	"architecture": "bert-base-uncased",
	"parameters": {
		"num_layers": 12,
		"hidden_size": 768,
		"num_attention_heads": 12,
		"intermediate_size": 3072
	},
	"training_data": {
		"dataset": "MockDataset1",
		"size": "10k",
		"epochs": 3,
		"batch_size": 32,
		"learning_rate": 5e-5
	},
	"evaluation_metrics": {
		"accuracy": 0.95,
		"f1_score": 0.94,
		"precision": 0.93,
		"recall": 0.92
	},
	"example_inputs": [
		"This is a sample input text for the mock model 1."
	],
	"example_outputs": [
		"This is a sample output text generated by the mock model 1."
	]
};

// Use the function to get the formatted string
console.log(getDaysAgo(model.last_modified));
