[build-system]
requires = ["setuptools>=74.0.0,<75.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "amapy-utils"
version = "1.0.1"
description = "A utility package that provides common functionality shared across the ama ecosystem."
readme = "README.md"
authors = [
    { name = "Swarup Mahanti", email = "swarup.mahanti@roche.com" }
]
maintainers = [
    { name = "Swarup Mahanti", email = "swarup.mahanti@roche.com" }
]
license = { text = "Copyright (c) 2024 Roche Diagnostics Computation Science & Informatics" }
requires-python = ">=3.12,<3.13"  # "==3.12.*"
dependencies = [
    "aiofiles==25.1.*",
    "colorama==0.4.*",
    "crcmod==1.*",
    "psutil==7.2.*",
    "pyopenssl==26.0.*",
    "pypager==3.0.1",
    "pytz==2026.1.*",
    "pyyaml==6.0.*",
    "requests==2.33.*",
    "ruamel.yaml==0.19.*",
    "speedtest-cli==2.1.*",
    "tabulate==0.10.*",
    "tqdm==4.67.*"
]

[tool.setuptools.packages.find]
include = ["*"]
namespaces = false
