[build-system]
requires = ["setuptools>=74.0.0,<75.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "amapy-plugin-s3"
version = "1.0.2"
description = "The S3 plugin for the ama project."
readme = "README.md"
authors = [
    { name = "Swarup Mahanti", email = "swarup.mahanti@roche.com" }
]
maintainers = [
    { name = "Swarup Mahanti", email = "swarup.mahanti@roche.com" }
]
license = { text = "Copyright (c) 2024 Roche Diagnostics Computation Science & Informatics" }
requires-python = ">=3.12,<3.13"  # "==3.12.*"
dependencies = [
    "aioboto3==13.0.*",
    "amapy-contents==1.1.*",
    "amapy-pluggy==1.1.*",
    "amapy-utils==1.1.*",
    "backoff==2.2.*",
    "urllib3==2.2.*"
]

[project.optional-dependencies]
test = [
    "moto==5.0.18",
]

[tool.setuptools.packages.find]
include = ["*"]
namespaces = false
