[build-system]
requires = ["setuptools>=74.0.0,<75.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "amapy-server"
version = "1.1.0"
description = "The server-side component of the ama project."
readme = "README.md"
authors = [
    { name = "Swarup Mahanti", email = "swarup.mahanti@roche.com" }
]
maintainers = [
    { name = "Swarup Mahanti", email = "swarup.mahanti@roche.com" }
]
license = { text = "Copyright (c) 2024 Roche Diagnostics Computation Science & Informatics" }
requires-python = ">=3.12,<3.13"

dependencies = [
    "aioshutil==1.5",
    "amapy-pluggy==1.1.*",
    "amapy-plugin-gcs==1.1.*",
    "amapy-plugin-s3==1.1.*",
    "amapy-utils==1.1.*",
    "elasticsearch==8.17.*",
    "google-auth-oauthlib==1.2.*", # same as amapy-core
    "peewee==3.17.*",
    "psycopg2==2.9.*",
    "sentence-transformers==3.4.*",
    "wtf-peewee==3.0.*",
    # Flask related packages
    "Flask==2.1.1",
    "Flask-Admin==1.6.0",
    "flask-cors==3.0.10",
    "Flask-Dance==7.0.0",
    "Flask-Login==0.6.3",
    "Jinja2==3.1.*", # amapy-core
    "Werkzeug==2.0.1",
    "gunicorn==20.1.*",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages]
find = { }

[tool.setuptools.package-data]
"amapy_server" = [
    "configs/yamls/*.yaml",
    "templates/**",
    "static/**"
]

[project.scripts]
ama-server = "amapy_server.main:main"
